In [1]:
!pip install pandas scikit-learn nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

data = {
    "resume": [
        "Python machine learning data analysis pandas numpy",
        "Java spring boot backend developer microservices",
        "Python deep learning tensorflow keras NLP",
        "SQL data analyst excel power bi tableau"
    ]
}

df = pd.DataFrame(data)
df

                                              resume
0  Python machine learning data analysis pandas n...
1   Java spring boot backend developer microservices
2          Python deep learning tensorflow keras NLP
3            SQL data analyst excel power bi tableau

In [3]:
job_description = "Python machine learning deep learning data science"

In [4]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    return text

df['clean_resume'] = df['resume'].apply(clean_text)
job_clean = clean_text(job_description)

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()

all_text = df['clean_resume'].tolist() + [job_clean]

tfidf_matrix = vectorizer.fit_transform(all_text)

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

resume_vectors = tfidf_matrix[:-1]
job_vector = tfidf_matrix[-1]

scores = cosine_similarity(resume_vectors, job_vector)

In [7]:
df['score'] = scores

df = df.sort_values(by='score', ascending=False)

df

,resume,clean_resume,score
0,Python machine learning data analysis pandas n...,python machine learning data analysis pandas n...,0.489514
2,Python deep learning tensorflow keras NLP,python deep learning tensorflow keras nlp,0.418963
3,SQL data analyst excel power bi tableau,sql data analyst excel power bi tableau,0.079044
1,Java spring boot backend developer microservices,java spring boot backend developer microservices,0.000000

In [10]:
def skill_gap(resume, job):

    resume_words = set(resume.split())
    job_words = set(job.split())

    missing = job_words - resume_words

    return ", ".join(missing)

df['missing_skills'] = df['clean_resume'].apply(lambda x: skill_gap(x, job_clean))
df['score'] = (df['score'] * 100).round(2)
df

,resume,clean_resume,score,missing_skills
0,Python machine learning data analysis pandas n...,python machine learning data analysis pandas n...,48.95,"science, deep"
2,Python deep learning tensorflow keras NLP,python deep learning tensorflow keras nlp,41.90,"science, data, machine"
3,SQL data analyst excel power bi tableau,sql data analyst excel power bi tableau,7.90,"science, learning, python, deep, machine"
1,Java spring boot backend developer microservices,java spring boot backend developer microservices,0.00,"science, learning, python, data, deep, machine"